version: '3.9'

services:
  fastapi:
    build: .
    container_name: fastapi_service
    command: uvicorn app.api:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    restart: unless-stopped

  gradio:
    build: .
    container_name: gradio_service
    command: python app/gradio_app.py
    ports:
      - "7860:7860"
    restart: unless-stopped

  rag_gradio:
    build: .
    command: python app/rag_gradio_app.py
    ports:
      - "7861:7861"

  rag_api:
    build: .
    command: uvicorn app.rag_api:app --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"
