label_knowledge = {
    "absurd": "Absurd films feature illogical, surreal, or nonsensical elements. Example: Monty Python's The Meaning of Life.",
    "action": "Action films emphasize physical feats, fights, chases, and stunts. Example: Die Hard.",
    "adult comedy": "Adult comedy contains mature humor, often with sexual or risqué themes. Example: American Pie.",
    "allegory": "Allegorical films use symbolic figures and actions to convey deeper meanings. Example: Animal Farm.",
    "alternate history": "Alternate history explores 'what if' scenarios diverging from real historical events. Example: The Man in the High Castle.",
    "alternate reality": "Alternate reality stories take place in worlds different from our own. Example: The Matrix.",
    "anti war": "Anti-war films critique or oppose war and its consequences. Example: Apocalypse Now.",
    "atmospheric": "Atmospheric films focus on mood, visuals, and tension. Example: Blade Runner.",
    "autobiographical": "Autobiographical films are based on the creator's own life. Example: 8½ by Federico Fellini.",
    "avant garde": "Avant-garde films experiment with unconventional techniques and narratives. Example: Un Chien Andalou.",
    "blaxploitation": "Blaxploitation films feature Black actors and urban settings, often with social commentary. Example: Shaft.",
    "bleak": "Bleak films have a grim, hopeless, or depressing tone. Example: Requiem for a Dream.",
    "boring": "Boring films are perceived as dull or unengaging. Example: Some viewers consider Solaris (1972) slow and boring.",
    "brainwashing": "Brainwashing themes involve manipulation and control of minds. Example: The Manchurian Candidate.",
    "christian film": "Christian films focus on Christian themes, values, or stories. Example: The Passion of the Christ.",
    "claustrophobic": "Claustrophobic films evoke a sense of confinement or restricted space. Example: Buried.",
    "clever": "Clever films feature smart plots, witty dialogue, or inventive storytelling. Example: The Usual Suspects.",
    "comedy": "Comedy films aim to amuse and entertain through humor. Example: Airplane!.",
    "comic": "Comic films are lighthearted and often based on comic books or strips. Example: Scott Pilgrim vs. the World.",
    "cruelty": "Cruelty involves suffering or abuse intentionally inflicted. Example: Saw.",
    "cult": "Cult films are often strange or niche and attract small, loyal audiences. Example: The Rocky Horror Picture Show.",
    "cute": "Cute films are charming, endearing, or visually appealing. Example: My Neighbor Totoro.",
    "dark": "Dark films explore grim, disturbing, or morally ambiguous themes. Example: Se7en.",
    "depressing": "Depressing films evoke sadness or despair. Example: Grave of the Fireflies.",
    "dramatic": "Dramatic stories focus on emotional, social, or moral conflict. Example: The Godfather.",
    "entertaining": "Entertaining films are enjoyable and engaging for audiences. Example: Guardians of the Galaxy.",
    "fantasy": "Fantasy films feature magical, supernatural, or imaginary elements. Example: The Lord of the Rings.",
    "feel-good": "Feel-good stories are emotionally satisfying and heartwarming. Example: Amélie.",
    "flashback": "Flashback films use scenes set in earlier times to provide context. Example: Citizen Kane.",
    "good versus evil": "Good versus evil stories center on the struggle between opposing moral forces. Example: Star Wars.",
    "gothic": "Gothic stories mix horror with romance or mystery. Example: Crimson Peak.",
    "grindhouse film": "Grindhouse films are low-budget, exploitative, and often sensational. Example: Planet Terror.",
    "haunting": "Haunting films leave a lingering emotional or psychological impact. Example: The Others.",
    "historical": "Historical films are set in or based on real past events. Example: Schindler's List.",
    "historical fiction": "Historical fiction blends real history with fictional elements. Example: Titanic.",
    "home movie": "Home movies are amateur films, often documenting personal events. Example: The Blair Witch Project (styled as found footage).",
    "horror": "Horror involves fear, shock, and the supernatural. Example: The Exorcist.",
    "humor": "Humor is the quality of being amusing or comical. Example: Dumb and Dumber.",
    "insanity": "Insanity themes explore madness, mental illness, or psychological breakdown. Example: Black Swan.",
    "inspiring": "Inspiring films uplift and motivate the viewer. Example: The Pursuit of Happyness.",
    "intrigue": "Intrigue films involve suspense, secrets, and complex plots. Example: Tinker Tailor Soldier Spy.",
    "magical realism": "Magical realism blends realistic settings with magical elements. Example: Pan's Labyrinth.",
    "melodrama": "Melodramas emphasize exaggerated emotions and interpersonal conflicts. Example: Terms of Endearment.",
    "murder": "Murder-themed plots involve killings, crime, and investigations. Example: Zodiac.",
    "mystery": "Mystery films revolve around solving puzzles or crimes. Example: Knives Out.",
    "neo noir": "Neo-noir updates classic film noir themes with modern sensibilities. Example: Drive.",
    "non fiction": "Non-fiction films depict real events, people, or facts. Example: Bowling for Columbine.",
    "paranormal": "Paranormal films involve supernatural phenomena beyond scientific explanation. Example: Paranormal Activity.",
    "philosophical": "Philosophical films explore deep questions about existence, reality, or ethics. Example: Waking Life.",
    "plot twist": "Plot twist films feature unexpected changes in the storyline. Example: The Sixth Sense.",
    "pornographic": "Pornographic films depict explicit sexual content. Example: Deep Throat.",
    "prank": "Prank films involve practical jokes or trickery. Example: Jackass: The Movie.",
    "psychedelic": "Psychedelic films use surreal visuals and sounds to evoke altered states. Example: 2001: A Space Odyssey.",
    "psychological": "Psychological films focus on mental states, emotions, and mind games. Example: Fight Club.",
    "queer": "Queer films explore LGBTQ+ themes or characters. Example: Moonlight.",
    "realism": "Realism strives for authentic, true-to-life representation. Example: Bicycle Thieves.",
    "revenge": "Revenge films center on characters seeking retribution. Example: Oldboy.",
    "romantic": "Romantic plots explore love and relationships. Example: The Notebook.",
    "sadist": "Sadist themes involve deriving pleasure from inflicting pain. Example: The Night Porter.",
    "satire": "Satire uses humor, irony, or exaggeration to criticize or mock. Example: Dr. Strangelove.",
    "science fiction": "Science fiction explores futuristic, technological, or extraterrestrial concepts. Example: Interstellar.",
    "self-reflexive": "Self-reflexive films comment on their own creation or the filmmaking process. Example: Adaptation.",
    "shocking": "Shocking films aim to surprise or disturb the audience. Example: Audition.",
    "slapstick": "Slapstick comedy relies on exaggerated physical humor. Example: The Pink Panther.",
    "slow": "Slow films have a deliberate, unhurried pace. Example: 2001: A Space Odyssey.",
    "spoof": "Spoof films parody or lampoon other genres or works. Example: Spaceballs.",
    "stupid": "Stupid usually implies silly or exaggerated comedy. Example: Dumb and Dumber.",
    "stylized": "Stylized films use distinctive visual or narrative techniques. Example: Sin City.",
    "surreal": "Surreal films feature dreamlike, bizarre, or illogical elements. Example: Eraserhead.",
    "suspense": "Suspense films build tension and uncertainty. Example: Rear Window.",
    "thriller": "Thrillers are fast-paced, exciting, and often involve danger. Example: North by Northwest.",
    "tragic": "Tragic films end in disaster or evoke pity and sorrow. Example: Romeo + Juliet.",
    "twist ending": "Twist ending films conclude with an unexpected turn. Example: The Usual Suspects.",
    "uplifting": "Uplifting films inspire hope and positivity. Example: Billy Elliot.",
    "violence": "Violent stories include physical force and conflict. Example: John Wick.",
    "weird": "Weird films are unusual, eccentric, or unconventional. Example: Being John Malkovich.",
}
